name: pochi_trim
description: "A new Flutter project."
publish_to: "none"

version: 0.0.1+5

environment:
  sdk: 3.7.2

dependencies:
  cloud_firestore: 5.6.7
  cloud_functions: 5.5.0
  collection: 1.19.1
  cupertino_icons: 1.0.8
  firebase_analytics: 11.4.6
  firebase_auth: 5.5.3
  firebase_core: 3.13.0
  firebase_crashlytics: 4.3.5
  firebase_remote_config: 5.4.3
  fl_chart: 1.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: 2.6.1
  flutter_slidable: 4.0.0
  font_awesome_flutter: 10.8.0
  freezed_annotation: 2.4.4
  google_sign_in: 6.3.0
  in_app_review: 2.0.10
  intl: 0.20.2
  logging: 1.3.0
  package_info_plus: 8.3.0
  path_provider: 2.1.5
  purchases_flutter: 8.8.1
  riverpod: 2.6.1
  riverpod_annotation: 2.6.1
  share_plus: 11.0.0
  shared_preferences: 2.5.3
  skeletonizer: 1.4.3
  url_launcher: 6.3.1

dev_dependencies:
  build_runner: 2.4.15
  cider: 0.2.8
  custom_lint: 0.7.3
  flutter_launcher_icons: 0.14.3
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.5.8
  json_serializable: 6.9.5
  mockito:
  mocktail: 1.0.4
  pedantic_mono: 1.30.3
  riverpod_generator: 2.6.4
  riverpod_lint: 2.6.4

flutter:
  uses-material-design: true
