name: pochi_trim
description: "A new Flutter project."
publish_to: "none"

version: 1.0.1+20

environment:
  sdk: 3.9.2

dependencies:
  cloud_firestore: 6.1.0
  cloud_functions: 6.0.4
  collection: 1.19.1
  cupertino_icons: 1.0.8
  dio: 5.9.0
  email_validator: 3.0.0
  firebase_analytics: 12.0.4
  firebase_auth: 6.1.2
  firebase_core: 4.2.1
  firebase_crashlytics: 5.0.4
  firebase_remote_config: 6.1.1
  fl_chart: 1.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 3.0.3
  flutter_slidable: 4.0.3
  font_awesome_flutter: 10.12.0
  freezed_annotation: 3.1.0
  google_sign_in: 7.2.0
  in_app_review: 2.0.11
  # FlutterのSDKによりピン留めされているため、バージョンを指定しない
  # https://github.com/dart-lang/sdk/blob/main/docs/Flutter-Pinned-Packages.md
  intl: any
  logging: 1.3.0
  package_info_plus: 9.0.0
  purchases_flutter: 9.5.0
  riverpod_annotation: 3.0.3
  share_plus: 12.0.1
  shared_preferences: 2.5.3
  skeletonizer: 2.1.0
  tutorial_coach_mark: 1.3.3
  url_launcher: 6.3.2

dev_dependencies:
  build_runner: 2.7.1
  cider: 0.2.8
  custom_lint: 0.8.0
  flutter_launcher_icons: 0.14.4
  flutter_test:
    sdk: flutter
  freezed: 3.2.3
  json_serializable: 6.11.1
  mockito:
  mocktail: 1.0.4
  pedantic_mono: 1.34.0
  riverpod_generator: 3.0.3
  riverpod_lint: 3.0.3

flutter:
  uses-material-design: true
